select * from customer;



--Q1. What is the total revenue generated by male vs. female customers?
select gender , sum(purchase_amount) as revenue from customer group by gender;


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, discount_applied, purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer);
 


-- Q3. Which are the top 5 products with the highest average review rating?
select top 5 item_purchased , AVG(review_rating) as avg_rating from customer 
group by item_purchased order by avg_rating Desc;


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT 
    shipping_type,
    AVG(purchase_amount) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type
ORDER BY avg_purchase_amount DESC;


--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

SELECT 
    subscription_status, count(customer_id) as total_customers,
    AVG(purchase_amount) AS avg_purchase_amount,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue , avg_purchase_amount DESC;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
--the above que mean (which products rely heavily on discounts to sell)
SELECT TOP 5
    item_purchased,
    COUNT(*) AS total_purchases,
    SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discounted_purchases,
    ROUND(
        SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2
    ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC;



--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;


--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status , count(customer_id) as repeat_buyers 
from customer 
where previous_purchases > 5 
group by subscription_status;
 
-- made a little changes here bcz the column 'age_group' we made earlier in vscode using python but it
--didnt reflect in thetable so we made here again

-- Add age_group column to the table
ALTER TABLE customer
ADD age_group VARCHAR(20);

-- Fill it with values based on age
UPDATE customer
SET age_group = CASE
    WHEN age < 30 THEN 'Young Adult'
    WHEN age BETWEEN 30 AND 44 THEN 'Adult'
    WHEN age BETWEEN 45 AND 59 THEN 'Middle-aged'
    ELSE 'Senior'
END;

---- Verify
SELECT TOP 5 customer_id, age, age_group FROM customer;

--

--Q10. What is the revenue contribution of each age group? 


SELECT 
    age_group,     
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;